sudo: false

language: go

go:
- 1.9.x

go_import_path: github.com/prometheus/tsdb
install: true

script:
- go get github.com/golang/dep/cmd/dep
- dep ensure -v -vendor-only
- go test -timeout 5m github.com/prometheus/tsdb/...
