dist: trusty
language: go
go_import_path: github.com/prometheus/tsdb
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    go: 1.12.x
    install:
      - make deps
    script:
      - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install fuse
      - sudo modprobe fuse
      - sudo chmod 666 /dev/fuse
      - sudo chown root:$USER /etc/fuse.conf
      - sudo addgroup $USER fuse
      - sudo chmod a+rw /etc/fuse.conf
      - sudo echo user_allow_other >> /etc/fuse.conf
      - sudo chmod +x /bin/fusermount
      - make all
  - os: osx
    go: 1.12.x
    sudo: required
    install:
      - make deps
    script:
      - brew update
      - brew install caskroom/cask/brew-cask
      - brew cask install osxfuse
      - make all
  - os: windows
    go: 1.12.x
    before_install:
      - choco install make
    install:
       - make deps
    script:
      - make test

