dist: trusty
language: go
go_import_path: github.com/prometheus/tsdb
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    go: 1.12.x
    install:
      - make deps
    script:
      - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install fuse
      - sudo modprobe fuse
      - sudo addgroup $USER fuse
      # sudo echo user_allow_other >> /etc/fuse.conf has a permission issue because
      # the redirection of the file (>> /etc/fuse.conf) happens in the shell before sudo is run, so is done as a regular user.
      - sudo sh -c 'echo user_allow_other >>/etc/fuse.conf'
      - make all
  - os: osx
    go: 1.12.x
    sudo: required
    osx_image: xcode8.3
    script:
      - brew update
      - brew tap homebrew/cask
      - brew cask install osxfuse
      - sudo /Library/Filesystems/osxfuse.fs/Contents/Resources/load_osxfuse
      - sudo sysctl -w vfs.generic.osxfuse.tunables.allow_other=1
      - make all
  - os: windows
    go: 1.12.x
    before_install:
      - choco install make
    install:
      - make deps
    script:
      - make test

