# sudo is enabled because it provides more memory which was needed to run go test -race
sudo: required
dist: trusty
language: go

os:
- windows
- linux
- osx

go:
  - 1.9.x
  - 1.10.x

go_import_path: github.com/prometheus/tsdb

before_install:
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install make; fi

install:
  - go get -v -t ./...

script:
  # `check_license` target is omitted due to some missing license headers
  # `staticcheck` target is omitted due to linting errors
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then make test; else make style unused test; fi
